apply plugin: 'java-library'
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

dependencies {
    api project(":common-swagger")
    api project(":ftgo-consumer-service-api")
    api project(":ftgo-domain")

    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"

    implementation 'org.glassfish:jakarta.el:3.0.4'

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.rest-assured:rest-assured:5.3.2"
    testImplementation "com.jayway.jsonpath:json-path"
}
