spring.application.name=ftgo-courier-service
server.port=8084
spring.jpa.generate-ddl=false
spring.datasource.url=jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo_courier?useSSL=false
spring.datasource.username=mysqluser
spring.datasource.password=mysqlpw
spring.datasource.driver.class.name=com.mysql.jdbc.Driver
logging.level.org.hibernate.SQL=DEBUG
