
deployUrl=file:///Users/cer/.m2/testdeploy

eventuateMavenRepoUrl=https://dl.bintray.com/eventuateio-oss/eventuate-maven-release,file:///Users/cer/.m2/testdeploy

springBootVersion=3.2.5
springDependencyManagementPluginVersion=1.1.5
restAssuredVersion=5.4.0
micrometerVersion=1.12.5
eventuateUtilVersion=0.18.0.RELEASE

dockerComposePluginVersion=0.6.6
