spring.application.name=ftgo-consumer-service

server.port=8090

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.url=jdbc:mysql://${CONSUMER_SERVICE_DB_HOST:localhost}:${CONSUMER_SERVICE_DB_PORT:3306}/ftgo_consumer_service?useSSL=false&connectTimeout=30000&socketTimeout=30000&autoReconnect=true
spring.datasource.username=${CONSUMER_SERVICE_DB_USERNAME:mysqluser}
spring.datasource.password=${CONSUMER_SERVICE_DB_PASSWORD:mysqlpw}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=60000

spring.flyway.enabled=true
