dependencies {
    compile project(":ftgo-common")

    compile "org.springframework:spring-web:5.0.7.RELEASE"
    compile "com.fasterxml.jackson.core:jackson-databind:2.9.6"
    compile "org.slf4j:slf4j-api:1.7.25"

    testCompile "junit:junit:4.12"
    testCompile "org.springframework:spring-test:5.0.7.RELEASE"
}
