apply plugin: 'java-library'

dependencies {
    // TODO eliminate this - problem is value objects like Money need to be embeddable.
    // TODO https://en.wikibooks.org/wiki/Java_Persistence/Embeddables#Example_of_an_Embeddable_object_XML

    api "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"

    api group: 'com.fasterxml.jackson.core', name: 'jackson-core'
    api group: 'com.fasterxml.jackson.core', name: 'jackson-databind'
    api group: 'org.apache.commons', name: 'commons-lang3', version: '3.14.0'
    api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"

    implementation 'mysql:mysql-connector-java:8.0.33'

    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"

    runtimeOnly "javax.xml.bind:jaxb-api:2.3.1"
    runtimeOnly "org.glassfish.jaxb:jaxb-runtime:2.3.9"
    runtimeOnly "javax.activation:javax.activation-api:1.2.0"
}
