spring.application.name=ftgo-consumer-service

server.port=8082

spring.jpa.generate-ddl=false
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/ftgo_consumer?useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver.class.name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}

spring.flyway.enabled=true
