apiVersion: v1
kind: Service
metadata:
  name: ftgo-consumer-service
  labels:
    name: ftgo-consumer-service
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: ftgo-consumer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftgo-consumer-service
  template:
    metadata:
      labels:
        app: ftgo-consumer-service
    spec:
      containers:
        - name: ftgo-consumer-service
          image: ftgo-consumer-service-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: CONSUMER_SERVICE_DB_HOST
              value: ftgo-consumer-service-mysql
            - name: CONSUMER_SERVICE_DB_PORT
              value: "3306"
            - name: CONSUMER_SERVICE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: username
            - name: CONSUMER_SERVICE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: password
            - name: JAVA_OPTS
              value: -Xmx192m
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 15
---
