apiVersion: v1
kind: Service
metadata:
  name: ftgo-consumer-service-mysql
  labels:
    name: ftgo-consumer-service-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    role: ftgo-consumer-service-mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ftgo-consumer-service-mysql
spec:
  serviceName: "consumer-service-mysql"
  replicas: 1
  template:
    metadata:
      labels:
        role: ftgo-consumer-service-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ftgo-consumer-service-mysql
          image: mysql:5.7
          imagePullPolicy: Always
          ports:
              - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: password
            - name: MYSQL_DATABASE
              value: ftgo_consumer_service
          volumeMounts:
            - name: ftgo-consumer-service-mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: ftgo-consumer-service-mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
