spring.application.name=ftgo-consumer-service
server.port=8082

spring.jpa.generate-ddl=false
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo?useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mysqluser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysqlpw}
spring.datasource.driver.class.name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}
