server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftgo_consumer_service
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
