dependencies {
    implementation project(":common-swagger")
    implementation project(":ftgo-restaurant-service-api")
    implementation project(":ftgo-domain")

    implementation "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"

    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    testImplementation("io.rest-assured:rest-assured:$restAssuredVersion") {
        exclude group: 'org.apache.groovy'
    }
}
