#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE IF NOT EXISTS ftgo;
GRANT ALL PRIVILEGES ON ftgo.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS ftgo_consumer;
GRANT ALL PRIVILEGES ON ftgo_consumer.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION;
EOF
