buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.mysql:mysql-connector-j:8.0.33'
    }
}

plugins {
    id "org.flywaydb.flyway" version "7.15.0"
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.0.33'
}

flyway {
    url = "jdbc:mysql://${System.getenv('DOCKER_HOST_IP') ?: 'localhost'}/ftgo?useSSL=false"
    user = 'root'
    password = 'rootpassword'
    schemas = ['ftgo']
}
