plugins {
    id "org.flywaydb.flyway" version "9.22.3"
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.0.33'
}

flyway {
    url = "jdbc:mysql://${System.getenv('DOCKER_HOST_IP') ?: 'localhost'}/ftgo?sslMode=DISABLED&allowPublicKeyRetrieval=true"
    user = 'root'
    password = 'rootpassword'
    schemas = ['ftgo']
}
