apply plugin: 'java-library'

dependencies {
    api project(":ftgo-consumer-service-api")
    api project(":ftgo-restaurant-service-api")
    api project(":ftgo-order-service-api")
    api project(":ftgo-courier-service-api")
    api "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"

    api "org.springframework.boot:spring-boot-starter-test"
    api "org.junit.vintage:junit-vintage-engine"
    api("io.rest-assured:rest-assured:$restAssuredVersion") {
        exclude group: 'org.apache.groovy', module: 'groovy'
        exclude group: 'org.apache.groovy', module: 'groovy-xml'
    }
    api("io.rest-assured:json-path:$restAssuredVersion") {
        exclude group: 'org.apache.groovy', module: 'groovy'
        exclude group: 'org.apache.groovy', module: 'groovy-json'
    }
    api("io.rest-assured:xml-path:$restAssuredVersion") {
        exclude group: 'org.apache.groovy', module: 'groovy'
        exclude group: 'org.apache.groovy', module: 'groovy-xml'
    }
    api 'org.apache.groovy:groovy:4.0.21'
    api 'org.apache.groovy:groovy-xml:4.0.21'
    api 'org.apache.groovy:groovy-json:4.0.21'
    api "com.jayway.jsonpath:json-path:2.9.0"
}
