dependencies {
    api project(":ftgo-consumer-service-api")
    api project(":ftgo-restaurant-service-api")
    api project(":ftgo-order-service-api")
    api project(":ftgo-courier-service-api")
    implementation "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"


    implementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    implementation("io.rest-assured:rest-assured:$restAssuredVersion") {
        exclude group: 'org.codehaus.groovy'
    }
    implementation "com.jayway.jsonpath:json-path:2.3.0"

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.3'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.3'
}
