spring.application.name=ftgo-restaurant-service

server.port=8083

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.url=jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo_restaurant?useSSL=false
spring.datasource.username=mysqluser
spring.datasource.password=mysqlpw
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
