apply plugin: FtgoServicePlugin

dependencies {
    compile project(":ftgo-restaurant-service")

    compile "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"
    compile "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    compile "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"

    compile "mysql:mysql-connector-java:5.1.46"
    compile "org.flywaydb:flyway-core"

    testCompile "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
}

springBoot {
    mainClassName = 'net.chrisrichardson.ftgo.restaurantservice.main.FtgoRestaurantServiceMain'
}

bootJar {
    baseName = 'ftgo-restaurant-service-main'
    version = ''
}
